2022-08-26 13:20:20,391 INFO    MainThread:4519 [wandb_setup.py:_flush():76] Configure stats pid to 4519
2022-08-26 13:20:20,391 INFO    MainThread:4519 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2022-08-26 13:20:20,391 INFO    MainThread:4519 [wandb_setup.py:_flush():76] Loading settings from /home/developer/Desktop/continum/AdversarialTraning/train_tools/wandb/settings
2022-08-26 13:20:20,391 INFO    MainThread:4519 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-08-26 13:20:20,391 INFO    MainThread:4519 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train_tools/start_traning.py', 'program': 'start_traning.py'}
2022-08-26 13:20:20,391 INFO    MainThread:4519 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2022-08-26 13:20:20,391 INFO    MainThread:4519 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2022-08-26 13:20:20,391 INFO    MainThread:4519 [wandb_init.py:_log_setup():461] Logging user logs to /home/developer/Desktop/continum/AdversarialTraning/train_tools/wandb/run-20220826_132020-36bi3hhk/logs/debug.log
2022-08-26 13:20:20,391 INFO    MainThread:4519 [wandb_init.py:_log_setup():462] Logging internal logs to /home/developer/Desktop/continum/AdversarialTraning/train_tools/wandb/run-20220826_132020-36bi3hhk/logs/debug-internal.log
2022-08-26 13:20:20,392 INFO    MainThread:4519 [wandb_init.py:init():495] calling init triggers
2022-08-26 13:20:20,392 INFO    MainThread:4519 [wandb_init.py:init():499] wandb.init called with sweep_config: {}
config: {}
2022-08-26 13:20:20,392 INFO    MainThread:4519 [wandb_init.py:init():548] starting backend
2022-08-26 13:20:20,392 INFO    MainThread:4519 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-26 13:20:20,400 INFO    MainThread:4519 [backend.py:ensure_launched():217] starting backend process...
2022-08-26 13:20:20,404 INFO    MainThread:4519 [backend.py:ensure_launched():222] started backend process with pid: 4570
2022-08-26 13:20:20,405 INFO    MainThread:4519 [wandb_init.py:init():558] backend started and connected
2022-08-26 13:20:20,411 INFO    MainThread:4519 [wandb_init.py:init():634] updated telemetry
2022-08-26 13:20:20,421 INFO    MainThread:4519 [wandb_init.py:init():666] communicating run to backend with 30 second timeout
2022-08-26 13:20:21,279 WARNING MainThread:4519 [wandb_init.py:init():1064] interrupted
Traceback (most recent call last):
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 669, in init
    run, timeout=self.settings.init_timeout
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 223, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 324, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
